call_parentheses = "Always"
collapse_simple_statement = "Never"
indent_type = "Tabs"
indent_width = 4
line_endings = "Unix"
quote_style = "AutoPreferDouble"
sort_requires.enabled = true
space_after_function_names = "Never"
syntax = "Luau"
